# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tapkee_embed_cpp <- function(data, method, num_neighbors, target_dimension, gaussian_kernel_width, landmark_ratio, max_iteration, diffusion_map_timesteps, sne_perplexity, sne_theta, squishing_rate, spe_global_strategy, spe_num_updates, spe_tolerance, nullspace_shift, klle_shift, fa_epsilon, check_connectivity) {
    .Call(`_tapkee_tapkee_embed_cpp`, data, method, num_neighbors, target_dimension, gaussian_kernel_width, landmark_ratio, max_iteration, diffusion_map_timesteps, sne_perplexity, sne_theta, squishing_rate, spe_global_strategy, spe_num_updates, spe_tolerance, nullspace_shift, klle_shift, fa_epsilon, check_connectivity)
}

